import calendar
naptar = calendar.TextCalendar()
naptar.setfirstweekday(3)
naptar.pryear(2017)
print(naptar.formatmonth(2017,3))
d = calendar.LocaleTextCalendar(6, "HUNGARIAN")
d.pryear(2017)
d = calendar.LocaleTextCalendar(6, "japanese")
d.pryear(2017)
#d = calendar.LocaleTextCalendar(6, "nemo")
#d.pryear(2017)
d = calendar.LocaleTextCalendar(6, "HUNGARIAN")
d.pryear(2017)
#calendar.isleap()